### PR TITLE
Protect against drawing zero sized images, fixing Firefox crashes

### LINKED ISSUE #2232: Costume editor crash converting empty costume to vector
### Expected Behavior

No crash when converting an empty costume to vector

### Actual Behavior

The costume editor crashes.

### Steps to Reproduce

1. Create a new empty costume using the paint new costume button
2. Convert to bitmap
3. Convert to vector
4. The "Oops! Something went wrong." message should pop up.

### Operating System and Browser

Windows 10
Firefox 60.0.1

Console output:
```
IndexSizeError: Index or size is negative or greater than the allowed amount
lib.min.js:12
DOMException: Index or size is negative or greater than the allowed amount
raven.js:55:6
gui error Unhandled Error: getSubCanvas@https://preview.scratch.mit.edu/lib.min.js:12:117778
getSubRaster@https://preview.scratch.mit.edu/lib.min.js:12:117952
e.trim@https://preview.scratch.mit.edu/lib.min.js:30:209125
value@https://preview.scratch.mit.edu/lib.min.js:183:189494
e@https://preview.scratch.mit.edu/lib.min.js:12:10618
value@https://preview.scratch.mit.edu/lib.min.js:183:188207
updateClassInstance@https://preview.scratch.mit.edu/lib.min.js:230:46749
beginWork@https://preview.scratch.mit.edu/lib.min.js:230:48470
B@https://preview.scratch.mit.edu/lib.min.js:230:52447
o@https://preview.scratch.mit.edu/lib.min.js:230:52768
i@https://preview.scratch.mit.edu/lib.min.js:230:53004
d@https://preview.scratch.mit.edu/lib.min.js:230:56527
Y@https://preview.scratch.mit.edu/lib.min.js:230:56264
batchedUpdates@https://preview.scratch.mit.edu/lib.min.js:230:65805
ae@https://preview.scratch.mit.edu/lib.min.js:230:16595
$e@https://preview.scratch.mit.edu/lib.min.js:230:22922
d@https://cdn.ravenjs.com/3.22.1/raven.min.js:2:4444

Component stack: 
    in e
    in Connect(e)
    in div
    in div
    in div
    in div
    in W
    in InjectIntl(W)
    in e
    in Connect(e)
    in t
    in Connect(t)
    in e
    in Connect(e)
    in div
    in E
    in div
    in E
    in a
    in e
    in Connect(e)
    in InjectIntl(Connect(e))
    in e
    in Unknown
    in div
    in B
    in div
    in r
    in B
    in div
    in E
    in div
    in E
    in div
    in E
    in div
    in E
    in b
    in InjectIntl(b)
    in e
    in Connect(e)
    in t
    in Connect(t)
    in t
    in e
    in Unknown
    in IntlProvider
    in Connect(IntlProvider)
    in n
    in t
    in t
```

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-gui/issues/2232

### Proposed Changes

_Describe what this Pull Request does_

Do not `drawImage` using an image or canvas of zero width/height. Firefox will throw errors, and it will cause the paint editor to crash.

### Test Coverage

_Please show how you have added tests to cover your changes_

Fixes the following using mac/firefox:

- Add empty sprite, convert to bitmap and convert back empty-sprite-crash

---

@fsih i think this should get in for the smoke test tomorrow.

### CODE REVIEW

File: src/containers/paper-canvas.jsx [hunk 1]
```diff
@@ -126,11 +129,11 @@ class PaperCanvas extends React.Component {
...
         this.props.clearSelectedItems();
-        const raster = trim(getRaster());
-        if (raster.width === 0 || raster.height === 0) {
-            raster.remove();
+        const trimmedRaster = trim(getRaster());
+        if (trimmedRaster) {
+            paper.project.activeLayer.addChild(trimmedRaster);
         } else {
-            paper.project.activeLayer.addChild(raster);
+            getRaster().remove();
```
Comment (fsih) [inline src/containers/paper-canvas.jsx]: This else isn't needed. This is done in clearRaster.

**Review by fsih — DISMISSED** [review]
