### PR TITLE
Gradient outlines more fixes

### LINKED ISSUE #1224: Selecting a transparent line shows an apparent gradient?
### Expected Behavior
0 width strokes are always transparent

### Actual Behavior
Selecting a shape with 0 width shows a color

### Steps to Reproduce
1. Have a gradient outline
2. Set outline width to 0. Stroke color shows transparent
3. Deselect
4. Reselect. Now color shows as a gradient, even though it should show as transparent
bug gradient

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### LINKED ISSUE #1230: Can get "mixed" as one of the gradient colors when switching to ellipse/rectangle tools
### Expected Behavior
You can't draw "mixed" (the 3 circles icon), so when you switch to a drawing tool, the state should change away from "mixed"

### Actual Behavior
Color can show "mixed" when you switch to ellipse/rect tool

### Steps to Reproduce
1. Select the default cat
2. Go to outline dropdown and click on a gradient type. Both colors show "mixed"
3. Click on the ellipse tool. 2nd color still shows "mixed"

### Operating System and Browser
all

### LINKED ISSUE #1239: Changing a transparent fill or stroke to a gradient should create a black-to-white gradient
### Expected Behavior
Changing a transparent fill or stroke to a gradient should create a black-to-white gradient. This was decided by design team to feel lower floor than having a transparent-to-transparent or transparent-to-other-color gradient.

### Actual Behavior
If the color is set to transparent, and you add a gradient, it becomes a transparent-to-purple gradient

### Steps to Reproduce
transgradient

### Operating System and Browser
all

### PR DESCRIPTION
**Pull request by fsih**
### Resolves
Fixes https://github.com/LLK/scratch-paint/issues/1224
Fixes https://github.com/LLK/scratch-paint/issues/1239
Fixes https://github.com/LLK/scratch-paint/issues/1230

Test branch: https://fsih.github.io/scratch-gui/gradientOutlines/

### Proposed Changes
1. Show solid transparent instead of a gradient when the stroke width is 0
2. When you change a transparent, solid fill or stroke to one of the gradient types, it should change the color to a black-to-white gradient (instead of transparent-to-purple)
3. Remove the "mixed" (3 circles) color from any of the swatches when switching to the rectangle or ellipse tools

### Reason for Changes
1. We want the state to be "the stroke width is 0 iff the stroke color is transparent" since it can be confusing if nothing is drawing because one or the other is true
2. Design decision, half-transparent gradients feel conceptually higher ceiling
3. "mixed" is not a color you can paint with

### Test Coverage
Tested at a paint huddle
Tests planned later: https://github.com/LLK/scratch-paint/issues/1216

### CODE REVIEW

File: src/helper/style-path.js [hunk 1]
```diff
@@ -465,11 +465,23 @@ const getColorsFromSelection = function (selectedItems, bitmapMode) {
...
                     const strokeColor2String = secondary;
-                    const strokeGradientType = gradientType;
+                    let strokeGradientType = gradientType;
+
+                    if (strokeGradientType !== GradientTypes.SOLID &&
+                        item.strokeColor.gradient.stops.length === 2 &&
+                        item.strokeColor.gradient.stops[0].color.alpha === 0 &&
+                        item.strokeColor.gradient.stops[1].color.alpha === 0) {
+                        // Clear the gradient if both colors are transparent
+                        item.strokeColor = null;
```
Comment (adroitwhiz) [inline src/helper/style-path.js]: I feel like a function which *retrieves* color state from shapes should not modify those shapes' colors directly

**Review by ericrosenbaum — APPROVED** [review]
Reviewed interactively with @fsih and LGTM!

**Comment by fsih** [comment]
Filed another bug https://github.com/LLK/scratch-paint/issues/1248 for more tests
