### PR TITLE
Fix GH-122: change size inputs to input with custon onChange

### LINKED ISSUE #122: Change back `BufferedInput` to only update onBlur
The change made to account for the brush sizer and the eraser sizer (so that they would dynamically update the brush on a value change) was really just making them be a ranged input – so we should revert the functionality added to the `BufferedInput` component, and just change those (i.e. outline) to be a regular input.

This affects the the costume name input in an adverse way

### PR DESCRIPTION
**Pull request by mewtaylor**
This fixes #122 by reverting the changes to `bufferedInputHOC`, and adding a custom `onChange` handler to the mode tools for brush and eraser, and making them `Input` components. Same goes for the strok width indicator.

### CODE REVIEW

**Comment by paulkaplan** [comment]
Looks like you can't delete all the text in the box? Once I try to backspace to type a new value, it automatically makes it 0 or 1 (depending on the input).

**Comment by fsih** [comment]
I think the box should let you type whatever you want in it, and while it's invalid the internal state should default to 1 but it shouldn't update the box to say 1, until you unfocus maybe? This way you can make it through the transition state of having an empty field when trying to input a new number

**Comment by mewtaylor** [comment]
@paulkaplan @fsih I just adjusted the PR to have the ability to handle deletion as y'all mentioned through a new HOC. Thoughts?

File: src/components/forms/live-input-hoc.jsx [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+                this.handleChange(e);
+                e.target.blur();
+            }
+        }
+        handleFlush () {
+            this.setState({value: null});
+        }
+        handleChange (e) {
+            const isNumeric = typeof this.props.value === 'number';
+            const validatesNumeric = isNumeric ? !isNaN(e.target.value) : true;
```
Comment (fsih) [inline src/components/forms/live-input-hoc.jsx:34]: I think you need max value checking here. When you type in a huge number and press enter, the value in the field snaps back down to 400 but the image's stroke width doesn't. It looks like for huge values, the canvas just gives up.

File: src/components/forms/live-input-hoc.jsx [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+            bindAll(this, [
+                'handleChange',
+                'handleKeyPress',
+                'handleFlush'
+            ]);
+            this.state = {
+                value: null
+            };
+        }
+        handleKeyPress (e) {
```
Comment (fsih) [inline src/components/forms/live-input-hoc.jsx:23]: Nit: The function names handleChange, handleKeyPress, and handleFlush all kind of sound like the same thing, so it's hard to guess which one will be called by what and what order they'll happen in. Maybe the default wording on an input is just confusing. Do onKeyPress and onChange always both happen? Maybe we can come up with better names?

**Review by fsih — CHANGES_REQUESTED** [review]
Thanks! This HOC looks like it'll be really useful

File: src/components/forms/live-input-hoc.jsx (hunk 1 above)
Comment (mewtaylor) [reply src/components/forms/live-input-hoc.jsx:34]: @fsih great point – should we add this for the buffered input too, while I'm at it? /cc @paulkaplan

Comment (fsih) [reply src/components/forms/live-input-hoc.jsx:34]: It looks like the buffered inputs in the sprite info panel are handling max values OK already?

Comment (mewtaylor) [reply src/components/forms/live-input-hoc.jsx:34]: @fsih ah ok – odd, since it's the same functionality just in a different method. I'll take a look...

Comment (fsih) [reply src/components/forms/live-input-hoc.jsx:34]: They're probably handling it outside the component, and it's easier since it doesn't have a "live" factor. But yeah @paulkaplan would know better

**Comment by mewtaylor** [comment]
@fsih I added validation on max input, so that it "snaps" to the max if someone types an amount greater than that – is that the desired functionality?

Also w.r.t. the `handle` naming conventions – I was mostly trying to follow the conventions used already in `bufferedInputHOC`, but could change the names of the methods called if it's confusing for sure!

**Comment by fsih** [comment]
For the naming - that's fine, I think inputs are just confusing.

Sorry for dragging out the review, but I think we should do min validation too. Besides that everything looks good, thanks!

**Review by fsih — APPROVED** [review]
