### PR TITLE
Reshape curves

### LINKED ISSUE #1143: You can reshape by clicking anywhere on a shape's stroke
### Expected Behavior
When the stroke is very thick, you might expect clicking and dragging the stroke to move, instead of add reshape points

### Actual Behavior
It adds a reshape point unexpectedly far from the mouse click location

### Steps to Reproduce
In the paint editor, in the vector reshape tool
reshape outline

### Operating System and Browser
all

### PR DESCRIPTION
**Pull request by fsih**
### Resolves

Resolves https://github.com/LLK/scratch-paint/issues/1143

### Proposed Changes
Before
reshape before
After
reshape after

Reshaping only occurs if you click near the outline of the shape, not anywhere within the stroke

### Reason for Changes
A reshape point appearing far away from where the user clicks is unexpected

### Test Coverage
Tested manually

### CODE REVIEW

File: src/helper/selection-tools/reshape-tool.js [hunk 1]
```diff
@@ -249,14 +249,14 @@ class ReshapeTool extends paper.Tool {
         // or stroke (since those were invisible), just select the whole thing as if they clicked the fill.
```
Comment (adroitwhiz) [inline src/helper/selection-tools/reshape-tool.js]:
```suggestion
        // (since those were invisible), just select the whole thing as if they clicked the fill.
```

**Review by adroitwhiz — DISMISSED** [review]
Tested this out and it looks good; you might want to clarify one comment though

**Review by adroitwhiz — APPROVED** [review]

**Comment by fsih** [comment]
The lint issue might be https://github.com/yannickcr/eslint-plugin-react/issues/2728

**Comment by adroitwhiz** [comment]
@fsih yup, for now https://github.com/LLK/scratch-paint/pull/1189 works as a fix
