### PR TITLE
Skip processing of child paths in mergeEraser

### LINKED ISSUE #119: Eraser inverts color/holes
eraserbug

This one is probably in paper.js. If you make a shape with a tail and a loop and subtract a shape that goes through both the tail and the loop, part of the path gets inverted.

### LINKED ISSUE #120: Erasing through path with holes doesn't act right
1. Make a donut with the brush tool.

2a. Erase from outside the donut through to the other side of the donut.
erase-bug1

2b. Erase from inside the donut to outside the donut.
erase-bug2

### LINKED ISSUE #621: Shape loses color if you erase around a hole
### Expected Behavior
Erasing does not change colors

### Actual Behavior
Erased shape turns white

### Steps to Reproduce
erasehole
1. Erase a hole in a shape
2. Erase over the hole with a bigger eraser

### Operating System and Browser
Mac OSX Chrome

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves #621
Resolves #120
Resolves #119

### Proposed Changes

This PR modifies the shape Boolean processing loop in `Blobbiness.mergeEraser` to skip processing paths that are children of compound paths.

### Reason for Changes

Both child paths and their parents are included in the list of items that `mergeEraser` will attempt to merge with. If child paths are not specifically excluded, `mergeEraser` will attempt to operate on them twice: once with their parent path, and one with them on their own.

Fixing this greatly improves the reliability of eraser operations:

Before | After
-|-
mergeeraser-before | mergeeraser-after
mergeeraser-before-2 | mergeeraser-after-2

### CODE REVIEW

**Comment by fsih** [comment]
Wow, that looks great!

**Comment by adroitwhiz** [comment]
Related Bugs and Glitches posts:
- [Vector Glitches](https://scratch.mit.edu/discuss/topic/388559/)
- [Eraser Glitch](https://scratch.mit.edu/discuss/topic/337348/)
- [Animating Glitch](https://scratch.mit.edu/discuss/topic/388060/)
- [help?](https://scratch.mit.edu/discuss/topic/387335/)
- [glitch in the "kiran" srite](https://scratch.mit.edu/discuss/topic/386842/)
- [Eraser Tool Not working](https://scratch.mit.edu/discuss/topic/338079/)
- [The eraser isn't erasing](https://scratch.mit.edu/discuss/topic/385912/)
- [Scratch 3.0 Eraser Glitches](https://scratch.mit.edu/discuss/topic/384029/)
- [the Vector eraser still doesn't work?? :\\](https://scratch.mit.edu/discuss/topic/383887/)
- [Vector erase bug.](https://scratch.mit.edu/discuss/topic/381691/)
- [Vector Eraser Not Working Correctly](https://scratch.mit.edu/discuss/topic/381521/)
- [Eraser turns everything black.](https://scratch.mit.edu/discuss/topic/381207/)
- [vectors eraser is really annoying](https://scratch.mit.edu/discuss/topic/381242/)
- [The Vector Eraser Is Buggy](https://scratch.mit.edu/discuss/topic/348273/)

**Review by fsih — APPROVED** [review]
This is so good!! Thanks for wading through the blob code to find this!

File: src/helper/blob-tools/blob.js [hunk 1]
```diff
@@ -259,17 +263,15 @@ class Blobbiness {
...
                 class: paper.PathItem
             });
         }
 
         for (let i = items.length - 1; i >= 0; i--) {
-            // If a path is part of a compound path, that parent path will later be processed.
-            // Skip processing the child path so as not to double-process it.
-            if (isCompoundPathChild(items[i])) continue;
-
             // TODO handle compound paths
```
Comment (fsih) [inline src/helper/blob-tools/blob.js:275]: Maybe that's what this comment was referring to? =_=;

Comment (adroitwhiz) [reply src/helper/blob-tools/blob.js:275]: I was wondering about that... is it okay to remove those comments then?

Comment (fsih) [reply src/helper/blob-tools/blob.js:275]: We're handling them now, so I guess so!
